spring.application.name=gym-booking-system

spring.datasource.url=jdbc:postgresql://localhost:5433/mydatabase
spring.datasource.username=postgres
spring.datasource.password=password

spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true

spring.docker.compose.enabled=false

spring.data.redis.host=localhost
spring.data.redis.port=6379

jwt.secret = OMSMfITzp2sQ2lMnseVk7Ols42sQSmdDYaEgxBBfZO3
jwt.expiration = 1800000
refresh.expiration = 7